import Header from './components/Header'
import AuthContextProvider from './context/AuthContextProvider'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
        <Header/>
        {children}
        </AuthContextProvider>
        </body>

    </html>
  )
}
